// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace MMPD.Data.Models;

public partial class Department
{
    [Column("Id")]
    [Key]
    public int Id { get; set; }

    [StringLength(60)]
    [Required]
    public string? DeptName { get; set; }

    [Required]
    public int? Location { get; set; }

    [StringLength(60)]
    public string? DeptManager { get; set; }

    [StringLength(15)]
    public string? DeptPhone { get; set; }

    [StringLength(60)]
    public string? DeptEmail { get; set; }

    [StringLength(15)]
    public string? DeptFax { get; set; }

    [JsonIgnore]
    public DateTime? RecordAdd { get; set; }

    
    public bool? Active { get; set; } = true;

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual Location? DeptLocation { get; set; }
}