// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace MMPD.Data.Models;

public partial class Employee
{
    [Column("Id")]
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string? FirstName { get; set; }

    [Required]
    [StringLength(40)]
    public string? LastName { get; set; }

    [StringLength(50)]
    [Required]
    public string? JobTitle { get; set; }

    public bool? IsManager { get; set; } = false;

    [StringLength(15)]
    [Required]
    public string? PhoneNumber { get; set; }

    [StringLength(15)]
    public string? CellNumber { get; set; }

    [StringLength(8)]
    [Column(TypeName = "TEXT")]
    public string? Extension { get; set; }

    [StringLength(60)]
    [Required]
    public string? Email { get; set; }

    public string? NetworkId { get; set; }

    public string? EmpAvatar { get; set; }


    public int? Location { get; set; }

    public int? Department { get; set; }

    [JsonIgnore]
    public DateTime? RecordAdd { get; set; }

    
    public bool? Active { get; set; } = true;

    public virtual Department? EmpDepartment { get; set; }

    public virtual Location? EmpLocation { get; set; }
}