// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MMPD.Data.Models;

public partial class Loctype
{
    [Column("Id")]
    [Key]
    public int Id { get; set; }

    public string LoctypeName { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();
}